clarity_yandex_oauth_token_request:
    path: /yandex/oauth/token/request/{appName}
    defaults: { _controller: ClarityYandexOAuthBundle:OAuth:requestToken }
    methods: [GET]

clarity_yandex_oauth_token_exchange:
    path: /yandex/oauth/token/exchange
    defaults: { _controller: ClarityYandexOAuthBundle:OAuth:exchangeCodeToToken }
    methods: [GET]
